### ISSUE TITLE
Upper case when pressing `Shift`

### ISSUE THREAD

**Issue by eeeXun** [fcitx/fcitx5-chewing#12]
Is there any way to type upper case when pressing `Shift` while in chewing. Currently, when in chewing mode and press `Shift` to type any word, always lower case.
And I can't find where to setting it.
![image](https://user-images.githubusercontent.com/58657914/166090735-048f704a-d2cb-4097-b8cc-4578999984b0.png)

Environment:
fcitx5 5.0.15-1
fcitx5-chewing 5.0.10-1

**Comment by wengxt** [comment]
While it's possible to do that, how would one type lower case then? any suggestions? Do you know if other chewing input method does something differently? BTW, by default you can always press shift to switch to keyboard im if you configured it.

I believe it's a feature in libchewing though since lowercase is more frequently used.

**Comment by eeeXun** [comment]
Sorry for the late reply.
I move from Windows to Linux. In Windows, I found it's more intuitive to type uppercase when pressing shift.

In chewing mode, I think it's more often to type uppercase, for me. If I want to type lowercase, I would do what you said, `press shift to switch to change im`

**Comment by leafpool243** [comment]
> While it's possible to do that, how would one type lower case then? any suggestions? Do you know if other chewing input method does something differently? BTW, by default you can always press shift to switch to keyboard im if you configured it.
> 
> I believe it's a feature in libchewing though since lowercase is more frequently used.
@wengxt 
I would suggest this:
1. Hitting shift key once will toggle to eng+numbers keyboard[1] (more similar to most Chinese IMEs);
2. Holding shift key will type lowercase letters (current behavior); and
3. Hitting caps lock key will toggle to uppercase letters (hitting caps lock again would return to zhuyin mode)

[1]: I know that you can use the press shift to return to non-IME option, but I don’t like it because I don’t want that feature for non-IME keyboards (e.g. for Russian, etc.)

**Comment by wengxt** [comment]
I think this should be handled by libchewing.

BTW, there's some feature that you can use in fcitx if you need to type english word temporarily.
"Meta + ` " will launch quickphrase in fcitx that allows you to type English without switching input method, if that helps.

**Comment by eeeXun** [comment]
> "Meta + ` " will launch quickphrase in fcitx that allows you to type English without switching input method

That helps a lot. Thank you!
